package com.marshall.pyerite.corporationModule.wallet.model

import androidx.annotation.StringRes
import com.marshall.pyerite.R

internal object CorporationWalletJournalRef {
    fun categoryFor(refType: String): CorporationWalletJournalCategory {
        val type = refType.trim()
        return CATEGORY_BY_REF[type] ?: when {
            type.startsWith(PREFIX_CONTRACT) -> CorporationWalletJournalCategory.CONTRACT
            type.startsWith(PREFIX_BOUNTY) -> CorporationWalletJournalCategory.BOUNTY
            type.startsWith(PREFIX_PLANETARY) -> CorporationWalletJournalCategory.PLANETARY
            else -> CorporationWalletJournalCategory.OTHER
        }
    }

    @StringRes
    fun titleResFor(refType: String): Int =
        TITLE_RES_BY_REF[refType.trim()] ?: categoryFor(refType).titleRes

    private const val PREFIX_CONTRACT = "contract_"
    private const val PREFIX_BOUNTY = "bounty"
    private const val PREFIX_PLANETARY = "planetary_"

    private val TITLE_RES_BY_REF: Map<String, Int> = mapOf(
        "acceleration_gate_fee" to R.string.corporation_journal_ref_acceleration_gate_fee,
        "advertisement_listing_fee" to R.string.corporation_journal_ref_advertisement_listing_fee,
        "agent_donation" to R.string.corporation_journal_ref_agent_donation,
        "agent_location_services" to R.string.corporation_journal_ref_agent_location_services,
        "agent_miscellaneous" to R.string.corporation_journal_ref_agent_miscellaneous,
        "agent_mission_collateral_paid" to R.string.corporation_journal_ref_agent_mission_collateral_paid,
        "agent_mission_collateral_refunded" to
            R.string.corporation_journal_ref_agent_mission_collateral_refunded,
        "agent_mission_reward" to R.string.corporation_journal_ref_agent_mission_reward,
        "agent_mission_reward_corporation_tax" to
            R.string.corporation_journal_ref_agent_mission_reward_corporation_tax,
        "agent_mission_time_bonus_reward" to
            R.string.corporation_journal_ref_agent_mission_time_bonus_reward,
        "agent_mission_time_bonus_reward_corporation_tax" to
            R.string.corporation_journal_ref_agent_mission_time_bonus_reward_corporation_tax,
        "agent_security_services" to R.string.corporation_journal_ref_agent_security_services,
        "agent_services_rendered" to R.string.corporation_journal_ref_agent_services_rendered,
        "agents_preward" to R.string.corporation_journal_ref_agents_preward,
        "alliance_maintainance_fee" to R.string.corporation_journal_ref_alliance_maintainance_fee,
        "alliance_registration_fee" to R.string.corporation_journal_ref_alliance_registration_fee,
        "asset_safety_recovery_tax" to R.string.corporation_journal_ref_asset_safety_recovery_tax,
        "bounty" to R.string.corporation_journal_ref_bounty,
        "bounty_prize" to R.string.corporation_journal_ref_bounty_prize,
        "bounty_prize_corporation_tax" to R.string.corporation_journal_ref_bounty_prize_corporation_tax,
        "bounty_prizes" to R.string.corporation_journal_ref_bounty_prizes,
        "bounty_reimbursement" to R.string.corporation_journal_ref_bounty_reimbursement,
        "bounty_surcharge" to R.string.corporation_journal_ref_bounty_surcharge,
        "brokers_fee" to R.string.corporation_journal_ref_brokers_fee,
        "clone_activation" to R.string.corporation_journal_ref_clone_activation,
        "clone_transfer" to R.string.corporation_journal_ref_clone_transfer,
        "contraband_fine" to R.string.corporation_journal_ref_contraband_fine,
        "contract_auction_bid" to R.string.corporation_journal_ref_contract_auction_bid,
        "contract_auction_bid_corp" to R.string.corporation_journal_ref_contract_auction_bid_corp,
        "contract_auction_bid_refund" to R.string.corporation_journal_ref_contract_auction_bid_refund,
        "contract_auction_sold" to R.string.corporation_journal_ref_contract_auction_sold,
        "contract_brokers_fee" to R.string.corporation_journal_ref_contract_brokers_fee,
        "contract_brokers_fee_corp" to R.string.corporation_journal_ref_contract_brokers_fee_corp,
        "contract_collateral" to R.string.corporation_journal_ref_contract_collateral,
        "contract_collateral_deposited_corp" to
            R.string.corporation_journal_ref_contract_collateral_deposited_corp,
        "contract_collateral_payout" to R.string.corporation_journal_ref_contract_collateral_payout,
        "contract_collateral_refund" to R.string.corporation_journal_ref_contract_collateral_refund,
        "contract_deposit" to R.string.corporation_journal_ref_contract_deposit,
        "contract_deposit_corp" to R.string.corporation_journal_ref_contract_deposit_corp,
        "contract_deposit_refund" to R.string.corporation_journal_ref_contract_deposit_refund,
        "contract_deposit_sales_tax" to R.string.corporation_journal_ref_contract_deposit_sales_tax,
        "contract_price" to R.string.corporation_journal_ref_contract_price,
        "contract_price_payment_corp" to R.string.corporation_journal_ref_contract_price_payment_corp,
        "contract_reversal" to R.string.corporation_journal_ref_contract_reversal,
        "contract_reward" to R.string.corporation_journal_ref_contract_reward,
        "contract_reward_deposited" to R.string.corporation_journal_ref_contract_reward_deposited,
        "contract_reward_deposited_corp" to
            R.string.corporation_journal_ref_contract_reward_deposited_corp,
        "contract_reward_refund" to R.string.corporation_journal_ref_contract_reward_refund,
        "contract_sales_tax" to R.string.corporation_journal_ref_contract_sales_tax,
        "copying" to R.string.corporation_journal_ref_copying,
        "corporate_reward_payout" to R.string.corporation_journal_ref_corporate_reward_payout,
        "corporate_reward_tax" to R.string.corporation_journal_ref_corporate_reward_tax,
        "corporation_account_withdrawal" to
            R.string.corporation_journal_ref_corporation_account_withdrawal,
        "corporation_bulk_account_entry" to
            R.string.corporation_journal_ref_corporation_bulk_account_entry,
        "corporation_dividend_payment" to R.string.corporation_journal_ref_corporation_dividend_payment,
        "corporation_liquidation" to R.string.corporation_journal_ref_corporation_liquidation,
        "corporation_logo_change_cost" to R.string.corporation_journal_ref_corporation_logo_change_cost,
        "corporation_payment" to R.string.corporation_journal_ref_corporation_payment,
        "corporation_registration_fee" to R.string.corporation_journal_ref_corporation_registration_fee,
        "courier_mission_escrow" to R.string.corporation_journal_ref_courier_mission_escrow,
        "cspa" to R.string.corporation_journal_ref_cspa,
        "cspaofflinerefund" to R.string.corporation_journal_ref_cspaofflinerefund,
        "daily_goal_payouts" to R.string.corporation_journal_ref_daily_goal_payouts,
        "daily_goal_payout" to R.string.corporation_journal_ref_daily_goal_payouts,
        "daily_goal_reward" to R.string.corporation_journal_ref_daily_goal_payouts,
        "datacore_fee" to R.string.corporation_journal_ref_datacore_fee,
        "dna_modification_fee" to R.string.corporation_journal_ref_dna_modification_fee,
        "docking_fee" to R.string.corporation_journal_ref_docking_fee,
        "duel_wager_escrow" to R.string.corporation_journal_ref_duel_wager_escrow,
        "duel_wager_payment" to R.string.corporation_journal_ref_duel_wager_payment,
        "duel_wager_refund" to R.string.corporation_journal_ref_duel_wager_refund,
        "ess_escrow_transfer" to R.string.corporation_journal_ref_ess_escrow_transfer,
        "factory_slot_rental_fee" to R.string.corporation_journal_ref_factory_slot_rental_fee,
        "gm_cash_transfer" to R.string.corporation_journal_ref_gm_cash_transfer,
        "industry_job" to R.string.corporation_journal_ref_industry_job,
        "industry_job_tax" to R.string.corporation_journal_ref_industry_job_tax,
        "infrastructure_hub_maintenance" to
            R.string.corporation_journal_ref_infrastructure_hub_maintenance,
        "insurance" to R.string.corporation_journal_ref_insurance,
        "item_exchange" to R.string.corporation_journal_ref_item_exchange,
        "item_trader_payment" to R.string.corporation_journal_ref_item_trader_payment,
        "jump_clone_activation_fee" to R.string.corporation_journal_ref_jump_clone_activation_fee,
        "jump_clone_installation_fee" to R.string.corporation_journal_ref_jump_clone_installation_fee,
        "kill_right_fee" to R.string.corporation_journal_ref_kill_right_fee,
        "lp_store" to R.string.corporation_journal_ref_lp_store,
        "manufacturing" to R.string.corporation_journal_ref_manufacturing,
        "market_escrow" to R.string.corporation_journal_ref_market_escrow,
        "market_fine_paid" to R.string.corporation_journal_ref_market_fine_paid,
        "market_transaction" to R.string.corporation_journal_ref_market_transaction,
        "medal_creation" to R.string.corporation_journal_ref_medal_creation,
        "medal_issued" to R.string.corporation_journal_ref_medal_issued,
        "mission_completion" to R.string.corporation_journal_ref_mission_completion,
        "mission_cost" to R.string.corporation_journal_ref_mission_cost,
        "mission_reward" to R.string.corporation_journal_ref_mission_reward,
        "mission_time_bonus" to R.string.corporation_journal_ref_mission_time_bonus,
        "office_rental_fee" to R.string.corporation_journal_ref_office_rental_fee,
        "operation_bonus" to R.string.corporation_journal_ref_operation_bonus,
        "opportunity_reward" to R.string.corporation_journal_ref_opportunity_reward,
        "planetary_construction" to R.string.corporation_journal_ref_planetary_construction,
        "planetary_export_tax" to R.string.corporation_journal_ref_planetary_export_tax,
        "planetary_import_tax" to R.string.corporation_journal_ref_planetary_import_tax,
        "player_donation" to R.string.corporation_journal_ref_player_donation,
        "player_trading" to R.string.corporation_journal_ref_player_trading,
        "project_discovery_reward" to R.string.corporation_journal_ref_project_discovery_reward,
        "project_discovery_tax" to R.string.corporation_journal_ref_project_discovery_tax,
        "reaction" to R.string.corporation_journal_ref_reaction,
        "release_of_impounded_property" to
            R.string.corporation_journal_ref_release_of_impounded_property,
        "repair_bill" to R.string.corporation_journal_ref_repair_bill,
        "reimbursement" to R.string.corporation_journal_ref_reimbursement,
        "research" to R.string.corporation_journal_ref_research,
        "reverse_engineering" to R.string.corporation_journal_ref_reverse_engineering,
        "season_challenge_reward" to R.string.corporation_journal_ref_season_challenge_reward,
        "security_processing_fee" to R.string.corporation_journal_ref_security_processing_fee,
        "shares" to R.string.corporation_journal_ref_shares,
        "skill_purchase" to R.string.corporation_journal_ref_skill_purchase,
        "sovereignity_bill" to R.string.corporation_journal_ref_sovereignity_bill,
        "store_purchase" to R.string.corporation_journal_ref_store_purchase,
        "store_purchase_refund" to R.string.corporation_journal_ref_store_purchase_refund,
        "structure_gate_jump" to R.string.corporation_journal_ref_structure_gate_jump,
        "transaction_tax" to R.string.corporation_journal_ref_transaction_tax,
        "upkeep_adjustment_fee" to R.string.corporation_journal_ref_upkeep_adjustment_fee,
        "war_ally_contract" to R.string.corporation_journal_ref_war_ally_contract,
        "war_fee" to R.string.corporation_journal_ref_war_fee,
        "war_fee_surrender" to R.string.corporation_journal_ref_war_fee_surrender,
    )

    private val CATEGORY_BY_REF: Map<String, CorporationWalletJournalCategory> = mapOf(
        "manufacturing" to CorporationWalletJournalCategory.INDUSTRY,
        "industry_job" to CorporationWalletJournalCategory.INDUSTRY,
        "industry_job_tax" to CorporationWalletJournalCategory.INDUSTRY,
        "copying" to CorporationWalletJournalCategory.INDUSTRY,
        "research" to CorporationWalletJournalCategory.INDUSTRY,
        "reverse_engineering" to CorporationWalletJournalCategory.INDUSTRY,
        "reaction" to CorporationWalletJournalCategory.INDUSTRY,
        "factory_slot_rental_fee" to CorporationWalletJournalCategory.INDUSTRY,
        "datacore_fee" to CorporationWalletJournalCategory.INDUSTRY,
        "market_escrow" to CorporationWalletJournalCategory.MARKET,
        "market_transaction" to CorporationWalletJournalCategory.MARKET,
        "transaction_tax" to CorporationWalletJournalCategory.MARKET,
        "brokers_fee" to CorporationWalletJournalCategory.MARKET,
        "market_fine_paid" to CorporationWalletJournalCategory.MARKET,
        "item_exchange" to CorporationWalletJournalCategory.MARKET,
        "item_trader_payment" to CorporationWalletJournalCategory.MARKET,
        "player_trading" to CorporationWalletJournalCategory.MARKET,
        "office_rental_fee" to CorporationWalletJournalCategory.TAX,
        "corporate_reward_tax" to CorporationWalletJournalCategory.TAX,
        "project_discovery_tax" to CorporationWalletJournalCategory.TAX,
        "asset_safety_recovery_tax" to CorporationWalletJournalCategory.TAX,
        "player_donation" to CorporationWalletJournalCategory.TRANSFER,
        "corporation_account_withdrawal" to CorporationWalletJournalCategory.TRANSFER,
        "corporation_bulk_account_entry" to CorporationWalletJournalCategory.TRANSFER,
        "corporation_payment" to CorporationWalletJournalCategory.TRANSFER,
        "corporation_dividend_payment" to CorporationWalletJournalCategory.TRANSFER,
        "gm_cash_transfer" to CorporationWalletJournalCategory.TRANSFER,
        "ess_escrow_transfer" to CorporationWalletJournalCategory.TRANSFER,
        "infrastructure_hub_maintenance" to CorporationWalletJournalCategory.FACILITY,
        "upkeep_adjustment_fee" to CorporationWalletJournalCategory.FACILITY,
        "structure_gate_jump" to CorporationWalletJournalCategory.FACILITY,
        "docking_fee" to CorporationWalletJournalCategory.FACILITY,
        "alliance_maintainance_fee" to CorporationWalletJournalCategory.FACILITY,
        "alliance_registration_fee" to CorporationWalletJournalCategory.FACILITY,
        "sovereignity_bill" to CorporationWalletJournalCategory.FACILITY,
        "agent_mission_reward" to CorporationWalletJournalCategory.MISSION,
        "agent_mission_reward_corporation_tax" to CorporationWalletJournalCategory.MISSION,
        "agent_mission_time_bonus_reward" to CorporationWalletJournalCategory.MISSION,
        "agent_mission_time_bonus_reward_corporation_tax" to CorporationWalletJournalCategory.MISSION,
        "agent_mission_collateral_paid" to CorporationWalletJournalCategory.MISSION,
        "agent_mission_collateral_refunded" to CorporationWalletJournalCategory.MISSION,
        "mission_completion" to CorporationWalletJournalCategory.MISSION,
        "mission_cost" to CorporationWalletJournalCategory.MISSION,
        "mission_reward" to CorporationWalletJournalCategory.MISSION,
        "mission_time_bonus" to CorporationWalletJournalCategory.MISSION,
        "agents_preward" to CorporationWalletJournalCategory.MISSION,
        "daily_goal_payouts" to CorporationWalletJournalCategory.MISSION,
        "daily_goal_payout" to CorporationWalletJournalCategory.MISSION,
        "daily_goal_reward" to CorporationWalletJournalCategory.MISSION,
        "clone_activation" to CorporationWalletJournalCategory.CLONE,
        "clone_transfer" to CorporationWalletJournalCategory.CLONE,
        "jump_clone_activation_fee" to CorporationWalletJournalCategory.CLONE,
        "jump_clone_installation_fee" to CorporationWalletJournalCategory.CLONE,
    )
}
